var DATA = [
      { id:0, label:"at.schauer.gregor.dormancy", link:"at/schauer/gregor/dormancy/package-summary.html", type:"package" },
      { id:1, label:"at.schauer.gregor.dormancy.Dormancy", link:"at/schauer/gregor/dormancy/Dormancy.html", type:"class" },
      { id:2, label:"at.schauer.gregor.dormancy.EntityPersisterConfiguration", link:"at/schauer/gregor/dormancy/EntityPersisterConfiguration.html", type:"class" },
      { id:3, label:"at.schauer.gregor.dormancy.closure", link:"at/schauer/gregor/dormancy/closure/package-summary.html", type:"package" },
      { id:4, label:"at.schauer.gregor.dormancy.closure.CollectionClosure", link:"at/schauer/gregor/dormancy/closure/CollectionClosure.html", type:"class" },
      { id:5, label:"at.schauer.gregor.dormancy.closure.DelegateClosure", link:"at/schauer/gregor/dormancy/closure/DelegateClosure.html", type:"class" },
      { id:6, label:"at.schauer.gregor.dormancy.closure.DormancyCloneClosure", link:"at/schauer/gregor/dormancy/closure/DormancyCloneClosure.html", type:"class" },
      { id:7, label:"at.schauer.gregor.dormancy.closure.DormancyClosure", link:"at/schauer/gregor/dormancy/closure/DormancyClosure.html", type:"class" },
      { id:8, label:"at.schauer.gregor.dormancy.closure.DormancyMergeClosure", link:"at/schauer/gregor/dormancy/closure/DormancyMergeClosure.html", type:"class" },
      { id:9, label:"at.schauer.gregor.dormancy.closure.ListClosure", link:"at/schauer/gregor/dormancy/closure/ListClosure.html", type:"class" },
      { id:10, label:"at.schauer.gregor.dormancy.closure.ResultClosure", link:"at/schauer/gregor/dormancy/closure/ResultClosure.html", type:"class" },
      { id:11, label:"at.schauer.gregor.dormancy.closure.SetClosure", link:"at/schauer/gregor/dormancy/closure/SetClosure.html", type:"class" },
      { id:12, label:"at.schauer.gregor.dormancy.interceptor", link:"at/schauer/gregor/dormancy/interceptor/package-summary.html", type:"package" },
      { id:13, label:"at.schauer.gregor.dormancy.interceptor.DormancyAdvisor", link:"at/schauer/gregor/dormancy/interceptor/DormancyAdvisor.html", type:"class" },
      { id:14, label:"at.schauer.gregor.dormancy.interceptor.DormancyAdvisor.Mode", link:"at/schauer/gregor/dormancy/interceptor/DormancyAdvisor.Mode.html", type:"class" },
      { id:15, label:"at.schauer.gregor.dormancy.interceptor.PersistenceEndpoint", link:"at/schauer/gregor/dormancy/interceptor/PersistenceEndpoint.html", type:"class" },
      { id:16, label:"at.schauer.gregor.dormancy.persister", link:"at/schauer/gregor/dormancy/persister/package-summary.html", type:"package" },
      { id:17, label:"at.schauer.gregor.dormancy.persister.AbstractContainerPersister", link:"at/schauer/gregor/dormancy/persister/AbstractContainerPersister.html", type:"class" },
      { id:18, label:"at.schauer.gregor.dormancy.persister.AbstractEntityPersister", link:"at/schauer/gregor/dormancy/persister/AbstractEntityPersister.html", type:"class" },
      { id:19, label:"at.schauer.gregor.dormancy.persister.CollectionPersister", link:"at/schauer/gregor/dormancy/persister/CollectionPersister.html", type:"class" },
      { id:20, label:"at.schauer.gregor.dormancy.persister.EntityPersister", link:"at/schauer/gregor/dormancy/persister/EntityPersister.html", type:"class" },
      { id:21, label:"at.schauer.gregor.dormancy.persister.FunctionPersister", link:"at/schauer/gregor/dormancy/persister/FunctionPersister.html", type:"class" },
      { id:22, label:"at.schauer.gregor.dormancy.persister.MapPersister", link:"at/schauer/gregor/dormancy/persister/MapPersister.html", type:"class" },
      { id:23, label:"at.schauer.gregor.dormancy.persister.NoOpEntityPersister", link:"at/schauer/gregor/dormancy/persister/NoOpEntityPersister.html", type:"class" },
      { id:24, label:"at.schauer.gregor.dormancy.util", link:"at/schauer/gregor/dormancy/util/package-summary.html", type:"package" },
      { id:25, label:"at.schauer.gregor.dormancy.util.AbstractDormancyUtils", link:"at/schauer/gregor/dormancy/util/AbstractDormancyUtils.html", type:"class" },
      { id:26, label:"at.schauer.gregor.dormancy.util.DormancyUtils", link:"at/schauer/gregor/dormancy/util/DormancyUtils.html", type:"class" },
      { id:27, label:"at.schauer.gregor.dormancy.util.HibernatePropertyAccessor", link:"at/schauer/gregor/dormancy/util/HibernatePropertyAccessor.html", type:"class" },
      { id:28, label:"at.schauer.gregor.dormancy.util.SpringPropertyAccessor", link:"at/schauer/gregor/dormancy/util/SpringPropertyAccessor.html", type:"class" }

    ];
